### ISSUE TITLE
Problem with dll paths

### ISSUE THREAD

**Issue by DeDrowhed** [mrglaster/S2GConverter#2]
[studiomdl.log](https://github.com/user-attachments/files/16922317/studiomdl.log)
![image](https://github.com/user-attachments/assets/e298630d-e681-48fc-8312-885299aa07eb)
![image](https://github.com/user-attachments/assets/e5b651cf-ccbc-499e-9059-a05f888f9aa2)

Everything works, but the utility doesn't see dll files from its own folder. After the whole process, the output is a working model, but it lacks texture. And, when trying to compile the model from qc file into HLMV, it hangs and then crashes because it can't find bmp for each part of the model. Although S2GConverter somehow manages to compile a working model despite this error, but it turns out purple and black. And also her hands change places, the model was for the right hand, now it is for the left hand.

P.s. - Before that there was a problem with finding S2GConverter. For some reason cmd tried to find it in the system32 folder. I had to stick the files there, and then I came to the current error.

**Comment by mrglaster** [comment]
Howdy! I see what's the problem, you execute the script when you are in folder System32. VTFLib looks for the dll files locally, in your case in directory  system32. You should execute the script when you are in the folder with the script, for example in 
/.../Desktop/S2GConverter. In this case it will work.

Привет, я понял в чем проблема. Ты запускаешь скрипт находясь в папке system32. VTFCmd ищет библиотеки локально. Задумывалось, что пользователь запускает скрипт находясь в каталоге с проектом, т.е. по пути /.../S2GConverter/  Запусти скрипт находясь в этой директории и всё должно пройти. 

Приятного использования

**Comment by DeDrowhed** [comment]
I still don't get it... Maybe I'm not running it right. The manual says: “Execute python script with the cmd”. And cmd I immediately look for in the System32 folder, I can't erase this path and specify another one. So I put all S2GConverter files there, including its dll. It should see them, because they are also in this folder.

**Comment by mrglaster** [comment]
just write cd /path/to/S2GConverter/ in console and then execute the script

**Comment by DeDrowhed** [comment]
Yes it worked, thank you very much:)

**Comment by mrglaster** [comment]
I'm glad to hear it)
